package com.skillswap.model.enums;

public enum NotificationType {
    SESSION_REQUEST, SESSION_ACCEPTED, SESSION_DECLINED, SESSION_COMPLETED,
    NEW_MESSAGE, NEW_RATING,
    MATCH_FOUND, MATCH_REQUEST, MATCH_ACCEPTED, MATCH_DECLINED
}
