server:
  port: 8080

spring:
  application:
    name: skillswap-backend
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:skillswap;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:SkillSwapSecretKeyForJWTTokenGeneration2024VeryLongSecretKeyThatIsAtLeast256BitsLongForHS256}
  expiration: 3600000
  refresh-expiration: 604800000

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

google:
  client-id: ${GOOGLE_CLIENT_ID:1043052570649-5lvenpma6kpv7fj89235r54dbbk6d07p.apps.googleusercontent.com}
  client-secret: ${GOOGLE_CLIENT_SECRET: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}

logging:
  level:
    com.skillswap: DEBUG
